name: circular_gradient_spinner
description: "Add beautiful circular gradient spinner as loading indicators"
version: 0.0.2
homepage: https://github.com/gabbygreat/circular_gradient_spinner.git

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
